//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCB_DPC_FRONT.DPCSuccessPage {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class DPCSuccessPage {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlAnchor homePage;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.Label Label1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.LinkButton btn_submit_close_modal;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lbl_confirmation_requestid;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lbl_confirmation_nameofapplicant;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lbl_confirmation_batchApplied;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lbl_confirmation_startDate;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lbl_confirmation_endDate;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lbl_confirmation_duration;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lbl_confirmation_location;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lbl_confirmation_applicationDateTime;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl div_submit_modal_confirmation;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.UpdatePanel up_modal_popup;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "15.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(DPCSuccessPage target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlAnchor @__BuildControlhomePage() {
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlAnchor();
            this.homePage = @__ctrl;
            @__ctrl.ID = "homePage";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Return To List Of Courses"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label1";
            @__ctrl.Text = "Label";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "labelSuccess");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControlbtn_submit_close_modal() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.btn_submit_close_modal = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btn_submit_close_modal";
            @__ctrl.Text = "×";
            @__ctrl.CssClass = "close";
            @__ctrl.Click -= new System.EventHandler(this.btn_submit_close_modal_Click);
            @__ctrl.Click += new System.EventHandler(this.btn_submit_close_modal_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control3() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Text = "Thank you for your application!";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control4() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Text = "Your Application is hereby acknowledged";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_confirmation_requestid() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_confirmation_requestid = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_confirmation_requestid";
            @__ctrl.Text = "Application ID: ";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control5() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Text = "<span class=\'modal-body-labelhighlight\'>E-Service Name:</span> Digital Proficienc" +
                "y Course";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_confirmation_nameofapplicant() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_confirmation_nameofapplicant = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_confirmation_nameofapplicant";
            @__ctrl.Text = "Applicant Name: ";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_confirmation_batchApplied() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_confirmation_batchApplied = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_confirmation_batchApplied";
            @__ctrl.Text = "Batch Applied For: ";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_confirmation_startDate() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_confirmation_startDate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_confirmation_startDate";
            @__ctrl.Text = "Start Date of Course: ";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_confirmation_endDate() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_confirmation_endDate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_confirmation_endDate";
            @__ctrl.Text = "End Date of Course: ";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_confirmation_duration() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_confirmation_duration = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_confirmation_duration";
            @__ctrl.Text = "Duration of Course: ";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_confirmation_location() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_confirmation_location = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_confirmation_location";
            @__ctrl.Text = "Location/Training centre: ";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_confirmation_applicationDateTime() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_confirmation_applicationDateTime = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_confirmation_applicationDateTime";
            @__ctrl.Text = "Date and Time of Application: ";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control6() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Text = "Note that an email has been sent to the email address as provided in the applicat" +
                "ion form";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control7() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Text = "Please note down your reference Id for future reference";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControldiv_submit_modal_confirmation() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.div_submit_modal_confirmation = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "div_submit_modal_confirmation";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "subject_modal");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n         \r\n            <div class=\"modal-content\">\r\n                <div class=" +
                        "\"modal-header\">\r\n                    "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl1;
            @__ctrl1 = this.@__BuildControlbtn_submit_close_modal();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n                <div class=\"modal-body\">\r\n             " +
                        "       <div class=\"modal-body-header\">\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control3();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<br />\r\n                        <br />\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control4();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<br />\r\n                        <br />\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl4;
            @__ctrl4 = this.@__BuildControllbl_confirmation_requestid();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </div>\r\n                    <div class=\"modal-body-eservice" +
                        "\">\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control5();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </div>\r\n                    <div class=\"modal-body-appdetai" +
                        "ls\">\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl6;
            @__ctrl6 = this.@__BuildControllbl_confirmation_nameofapplicant();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<br />\r\n                        <br />\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl7;
            @__ctrl7 = this.@__BuildControllbl_confirmation_batchApplied();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<br />\r\n                        <br />\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl8;
            @__ctrl8 = this.@__BuildControllbl_confirmation_startDate();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<br />\r\n                        <br />\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl9;
            @__ctrl9 = this.@__BuildControllbl_confirmation_endDate();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<br />\r\n                        <br />\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl10;
            @__ctrl10 = this.@__BuildControllbl_confirmation_duration();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<br />\r\n                        <br />\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl11;
            @__ctrl11 = this.@__BuildControllbl_confirmation_location();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<br />\r\n                        <br />\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl12;
            @__ctrl12 = this.@__BuildControllbl_confirmation_applicationDateTime();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("<br />\r\n                        <br />\r\n                    </div>\r\n             " +
                        "       <div class=\"modal-body-note\">\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl13;
            @__ctrl13 = this.@__BuildControl__control6();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </div>\r\n                    <div class=\"modal-body-referenc" +
                        "enote\">\r\n                        "));
            global::System.Web.UI.WebControls.Label @__ctrl14;
            @__ctrl14 = this.@__BuildControl__control7();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
                        " "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <!-- The Modal -->\r\n        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControldiv_submit_modal_confirmation();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.UpdatePanel @__BuildControlup_modal_popup() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            this.up_modal_popup = @__ctrl;
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            @__ctrl.ID = "up_modal_popup";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void @__BuildControlTree(global::NCB_DPC_FRONT.DPCSuccessPage.DPCSuccessPage @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n<style type=\"text/css\">\r\n    .auto-style1 {\r\n        height: 26px;\r\n    }" +
                        "\r\n\r\n    body {\r\n        font-family: Arial, Helvetica, sans-serif;\r\n    }\r\n\r\n   " +
                        " #s4-ribbonrow, .bottom-nav-container, .ms-cui-topBar2, .s4-notdlg, .s4-pr s4-ri" +
                        "bbonrowhidetitle, .s4-notdlg noindex, #ms-cui-ribbonTopBars, #s4-titlerow, #s4-p" +
                        "r s4-notdlg s4-titlerowhidetitle, #s4-leftpanel-content {\r\n        display: none" +
                        " !important;\r\n    }\r\n\r\n\r\n\r\n/* .s4-ca { */\r\n    /* margin-left: 0px !important; *" +
                        "/\r\n    /* margin-right: 0px !important; */\r\n/* } */\r\n\r\n.ms-core-navigation { \r\n " +
                        "    display: none; \r\n }\r\n\r\n/* #contentBox { */\r\n    /* margin-left: 0; */\r\n/* } " +
                        "*/\r\n\r\n.ms-webpart-titleText {\r\n    display: none;\r\n}\r\n\r\n.removeCaps {\r\n    text-" +
                        "transform: none !important;\r\n}\r\n\r\n/* The Modal (background) */\r\n.modal {\r\n    di" +
                        "splay: none; /* Hidden by default */\r\n    position: fixed; /* Stay in place */\r\n" +
                        "    z-index: 1; /* Sit on top */\r\n    padding-top: 100px; /* Location of the box" +
                        " */\r\n    left: 0;\r\n    top: 0;\r\n    width: 100%; /* Full width */\r\n    height: 1" +
                        "00%; /* Full height */\r\n    overflow: auto; /* Enable scroll if needed */\r\n    b" +
                        "ackground-color: rgb(0,0,0); /* Fallback color */\r\n    background-color: rgba(0," +
                        "0,0,0.4); /* Black w/ opacity */\r\n}\r\n\r\n/* Modal Content */\r\n.modal-content {\r\n  " +
                        "  background-color: #fefefe;\r\n    margin: auto;\r\n    padding: 20px;\r\n    border:" +
                        " 1px solid #888;\r\n    width: 80%;\r\n}\r\n\r\n/* The Close Button */\r\n.close {\r\n    co" +
                        "lor: #aaaaaa;\r\n    float: right;\r\n    font-size: 28px;\r\n    font-weight: bold;\r\n" +
                        "}\r\n\r\n    .close:hover,\r\n    .close:focus {\r\n        color: #000;\r\n        text-d" +
                        "ecoration: none;\r\n        cursor: pointer;\r\n    }\r\n\r\n.DPCApplication {\r\n    max-" +
                        "width: 100%;\r\n}\r\n\r\n    .DPCApplication .form-row:not(#btnRow) {\r\n        display" +
                        ": flex;\r\n        flex-wrap: wrap;\r\n        max-width: 80%;\r\n        margin: 0 au" +
                        "to;\r\n        float: none;\r\n    }\r\n\r\n#btnRow {\r\n    max-width: 85%;\r\n    margin: " +
                        "0 auto;\r\n    float: none;\r\n    text-align: center;\r\n}\r\n\r\n.DPCApplication .form-f" +
                        "ields.submit input {\r\n    width: 200px;\r\n    padding: 12px 30px;\r\n    margin: 0 " +
                        "auto;\r\n    border: none;\r\n    background-color: #799951;\r\n    color: #fff;\r\n    " +
                        "font-size: 20;\r\n    font-weight: 500;\r\n}\r\n\r\n.DPCApplication .form-fields.submit " +
                        "a {\r\n    text-decoration: none;\r\n    display: block;\r\n    width: 140px;\r\n    pad" +
                        "ding: 12px 30px;\r\n    margin: 0 auto;\r\n    border: none;\r\n    background-color: " +
                        "#799951;\r\n    color: #fff;\r\n    font-size: 20;\r\n    font-weight: 500;\r\n}\r\n\r\n    " +
                        ".DPCApplication .form-fields.submit input:hover, .DPCApplication .form-fields.su" +
                        "bmit a:hover {\r\n        background-color: #02AFEF;\r\n        cursor: pointer;\r\n  " +
                        "  }\r\n\r\n.DPCApplication .form-fields.submitTC input {\r\n    width: 250px;\r\n    pad" +
                        "ding: 12px 30px;\r\n    margin: 0 auto;\r\n    border: none;\r\n    background-color: " +
                        "#799951;\r\n    color: #fff;\r\n    font-size: 20;\r\n    font-weight: 500;\r\n}\r\n\r\n    " +
                        ".DPCApplication .form-fields.submitTC input:hover {\r\n        background-color: #" +
                        "02AFEF;\r\n        cursor: pointer;\r\n    }\r\n\r\n#txt_trainingCentreCode {\r\n    margi" +
                        "n-top: 4px;\r\n}\r\n\r\n.new-title-block {\r\n    width: 77%;\r\n    position: relative;\r\n" +
                        "    float: left;\r\n    margin-top: 30px;\r\n    margin-bottom: 15px;\r\n}\r\n\r\n.inner-s" +
                        "ub-title {\r\n    font-size: 52px;\r\n    font-weight: 700 !important;\r\n    color: #" +
                        "799951;\r\n}\r\n\r\n.sub-title {\r\n    font-size: 25px;\r\n    font-weight: 600 !importan" +
                        "t;\r\n    color: #799951;\r\n}\r\n\r\nspan.tooltip {\r\n    color: #ff0000;\r\n    font-size" +
                        ": 22px;\r\n    line-height: 26px;\r\n    cursor: pointer;\r\n}\r\n\r\nspan.mandatory {\r\n  " +
                        "  background: #465159;\r\n    color: #fff;\r\n    font-size: 12px;\r\n    line-height:" +
                        " 18px;\r\n    display: inline-block;\r\n    margin-left: 10px;\r\n    opacity: 0;\r\n   " +
                        " visibility: hidden;\r\n    position: absolute;\r\n    max-width: 0;\r\n    padding: 5" +
                        "px 8px;\r\n    border-radius: 3px;\r\n    transition: all 0.5s ease-out 0s;\r\n}\r\n\r\nsp" +
                        "an.tooltip:hover + span.mandatory {\r\n    opacity: 1;\r\n    visibility: visible;\r\n" +
                        "    max-width: 100%;\r\n}\r\n\r\n.form-fields {\r\n    position: relative;\r\n    margin: " +
                        "2% 2% 0;\r\n}\r\n\r\n    .form-fields.w100 {\r\n        width: 100%;\r\n    }\r\n\r\n        ." +
                        "form-fields.w100.field-med input, .form-fields.w100.field-med select {\r\n        " +
                        "    width: 46%;\r\n        }\r\n\r\n        .form-fields.w100.field-sm input, .form-fi" +
                        "elds.w100.field-sm select {\r\n            width: 29.3%;\r\n        }\r\n\r\n    .form-f" +
                        "ields.w50 {\r\n        width: 46%;\r\n    }\r\n\r\n    .form-fields.w30 {\r\n        width" +
                        ": 29.3%;\r\n    }\r\n\r\n    .form-fields.w70 {\r\n        width: 65.7%;\r\n    }\r\n\r\n@medi" +
                        "a screen and (max-width: 900px) {\r\n    .form-fields.w100.field-sm input, .form-f" +
                        "ields.w100.field-sm select {\r\n        width: 100%;\r\n    }\r\n\r\n    .form-fields.w3" +
                        "0 {\r\n        width: 100%;\r\n    }\r\n\r\n    .form-fields.w70 {\r\n        width: 100%;" +
                        "\r\n    }\r\n\r\n    .form-fields.w50 {\r\n        width: 100%;\r\n    }\r\n\r\n    .form-fiel" +
                        "ds.w100.field-med input, .form-fields.w100.field-med select {\r\n        width: 10" +
                        "0%;\r\n    }\r\n\r\n    .form-fields-sm-tit {\r\n        margin: 15px 0 0;\r\n    }\r\n\r\n   " +
                        " .form-fields {\r\n        position: relative;\r\n        margin: 5% 0 0;\r\n    }\r\n\r\n" +
                        "        .form-fields input[type=\'text\'], .form-fields select {\r\n            heig" +
                        "ht: 40px;\r\n        }\r\n}\r\n\r\n.form-row .form-fields label {\r\n    font-size: 14px;\r" +
                        "\n    line-height: 22px;\r\n    font-weight: bold;\r\n    color: #000000a3;\r\n}\r\n\r\n.fo" +
                        "rm-fields input[type=\'text\'], .form-fields select {\r\n    width: 100%;\r\n    heigh" +
                        "t: 35px;\r\n    border: 1px solid #c5c5c5;\r\n    font-size: 14px;\r\n    line-height:" +
                        " 22px;\r\n    color: #47515a;\r\n    border-radius: 0;\r\n    background-color: transp" +
                        "arent;\r\n    text-transform: capitalize;\r\n    padding: 0 15px;\r\n}\r\n\r\n.form-fields" +
                        " textarea {\r\n    width: 100%;\r\n    min-height: 100px;\r\n    border: 1px solid #c5" +
                        "c5c5;\r\n    font-size: 14px;\r\n    line-height: 22px;\r\n    color: #47515a;\r\n    bo" +
                        "rder-radius: 0;\r\n    background-color: transparent;\r\n    text-transform: capital" +
                        "ize;\r\n    padding: 15px;\r\n    margin-top: 4px;\r\n    font-family: \'Roboto\', sans-" +
                        "serif;\r\n}\r\n\r\n.form-fields input[type=\'checkbox\'] {\r\n    margin-right: 3.5%;\r\n   " +
                        " height: 17px;\r\n    width: 17px;\r\n}\r\n\r\nlabel.lbl_days_text {\r\n    vertical-align" +
                        ": text-bottom;\r\n    font-size: 16px !important;\r\n    font-weight: 500 !important" +
                        ";\r\n}\r\n\r\n#tblCourses {\r\n    border-collapse: collapse;\r\n    width: 100%;\r\n}\r\n\r\n  " +
                        "  #tblCourses td, #tblCourses th {\r\n        border: 1px solid #ddd;\r\n        pad" +
                        "ding: 8px;\r\n    }\r\n\r\n    #tblCourses tr:nth-child(even) {\r\n        background-co" +
                        "lor: #f2f2f2;\r\n    }\r\n\r\n    #tblCourses tr:hover {\r\n        background-color: #d" +
                        "dd;\r\n    }\r\n\r\n    #tblCourses thead {\r\n        padding-top: 12px;\r\n        paddi" +
                        "ng-bottom: 12px;\r\n        text-align: left;\r\n        background-color: #799951;\r" +
                        "\n        color: white;\r\n        font-weight: 600;\r\n    }\r\n\r\n.not-mandatory {\r\n  " +
                        "  margin-top: 4px;\r\n}\r\n\r\n.alert {\r\n    padding: 15px;\r\n    margin-bottom: 20px;\r" +
                        "\n    border: 1px solid transparent;\r\n    border-radius: 4px;\r\n    display: flex;" +
                        "\r\n    align-items: center;\r\n}\r\n\r\n    .alert:before {\r\n        content: \'\';\r\n    " +
                        "    position: absolute;\r\n        width: 0;\r\n        height: calc(100% - 44px);\r\n" +
                        "        border-left: 1px solid;\r\n        border-right: 2px solid;\r\n        borde" +
                        "r-bottom-right-radius: 3px;\r\n        border-top-right-radius: 3px;\r\n        left" +
                        ": 0;\r\n        top: 50%;\r\n        transform: translate(0,-50%);\r\n        height: " +
                        "20px;\r\n    }\r\n\r\n    .alert > .start-icon {\r\n        margin-right: 0;\r\n        mi" +
                        "n-width: 20px;\r\n        text-align: center;\r\n        margin-right: 5px;\r\n       " +
                        " float: left;\r\n    }\r\n\r\n.alert-simple.alert-info {\r\n    border: 1px solid rgba(6" +
                        ", 44, 241, 0.46);\r\n    background-color: rgba(7, 73, 149, 0.12156862745098039);\r" +
                        "\n    box-shadow: 0px 0px 2px #0396ff;\r\n    color: #0396ff;\r\n    transition: 0.5s" +
                        ";\r\n}\r\n\r\n.alert-info:hover {\r\n    background-color: rgba(7, 73, 149, 0.35);\r\n    " +
                        "transition: 0.5s;\r\n}\r\n\r\n#radioBtn_public {\r\n    margin-top: 10px;\r\n}\r\n\r\n#radioBt" +
                        "n_private {\r\n    margin-left: 10%;\r\n}\r\n\r\n\r\n.custom-gridview td, .custom-gridview" +
                        " th {\r\n    border: 1px solid #ddd;\r\n    padding: 8px;\r\n}\r\n\r\n.custom-gridview tr:" +
                        "nth-child(even) {\r\n    background-color: #f2f2f2;\r\n}\r\n\r\n.custom-gridview tr:hove" +
                        "r {\r\n    background-color: #ddd;\r\n}\r\n\r\n.custom-gridview th {\r\n    padding-top: 1" +
                        "2px;\r\n    padding-bottom: 12px;\r\n    text-align: left;\r\n    background-color: #7" +
                        "99951;\r\n    color: white;\r\n}\r\n\r\n.custom-gridview tbody tr td a {\r\n    text-decor" +
                        "ation: none;\r\n}\r\n\r\n.declaration {\r\n    color: red;\r\n}\r\n\r\n.declarationText {\r\n   " +
                        " display: inline-flex;\r\n    margin-top: 10px;\r\n    margin-left: 2%;\r\n    font-si" +
                        "ze: 14px;\r\n    font-weight: 500;\r\n}\r\n\r\n.inline {\r\n    display: inline-flex;\r\n   " +
                        " margin-top: 10px;\r\n    font-size: 15px;\r\n}\r\n\r\n    .inline input {\r\n        marg" +
                        "in-right: 8px;\r\n        margin-top: 3.5px;\r\n        font-size: 15px;\r\n    }\r\n\r\n " +
                        "   .inline label {\r\n        cursor: pointer;\r\n        margin-right: 25px;\r\n     " +
                        "   font-size: 15px;\r\n    }\n\n    body {\r\n    font-family: Arial, Helvetica, sans-" +
                        "serif;\r\n    padding: 0;\r\n    margin: 0;\r\n}\r\n\r\nh2 {\r\n    text-align: center;\r\n   " +
                        " font-size: 40px;\r\n    margin: 0;\r\n    font-weight: 300;\r\n    color: inherit;\r\n " +
                        "   padding: 50px;\r\n}\r\n\r\n.center {\r\n    text-align: center;\r\n}\r\n\r\nsection {\r\n    " +
                        "height: 5%;\r\n}\r\n\r\n/* NAVIGATION */\r\nnav {\r\n    width: 80%;\r\n    margin: 0 auto;\r" +
                        "\n    background: #fff;\r\n    padding: 5px 0;\r\n}\r\n\r\nnav ul {\r\n    list-style: none" +
                        ";\r\n    text-align: left;\r\n}\r\n\r\nnav ul li {\r\n    display: inline-block;\r\n}\r\n\r\nnav" +
                        " ul li a {\r\n    display: block;\r\n    padding: 15px;\r\n    text-decoration: none;\r" +
                        "\n    color: #aaa;\r\n    font-weight: 600;\r\n    text-transform: uppercase;\r\n    ma" +
                        "rgin: 0 10px;\r\n}\r\n\r\nnav ul li a,\r\nnav ul li a:after,\r\nnav ul li a:before {\r\n    " +
                        "transition: all .5s;\r\n}\r\n\r\nnav ul li a:hover {\r\n    color: #555;\r\n}\r\n\r\n/* stroke" +
                        " */\r\nnav.stroke ul li a,\r\nnav.fill ul li a {\r\n    position: relative;\r\n}\r\n\r\nnav." +
                        "stroke ul li a:after,\r\nnav.fill ul li a:after {\r\n    position: absolute;\r\n    bo" +
                        "ttom: 0;\r\n    left: 0;\r\n    right: 0;\r\n    margin: auto;\r\n    width: 0%;\r\n    co" +
                        "ntent: \'.\';\r\n    color: transparent;\r\n    background: #333;\r\n    height: 1px;\r\n}" +
                        "\r\n\r\nnav.stroke ul li a:hover:after {\r\n    width: 100%;\r\n}\r\n\r\nnav.fill ul li a {\r" +
                        "\n    transition: all 2s;\r\n}\r\n\r\nnav.fill ul li a:after {\r\n    text-align: left;\r\n" +
                        "    content: \'.\';\r\n    margin: 0;\r\n    opacity: 0;\r\n}\r\n\r\nnav.fill ul li a:hover " +
                        "{\r\n    color: #023f1c;\r\n    z-index: 1;\r\n}\r\n\r\nnav.fill ul li a:hover:after {\r\n  " +
                        "  z-index: -10;\r\n    animation: fill 1s forwards;\r\n    -webkit-animation: fill 1" +
                        "s forwards;\r\n    -moz-animation: fill 1s forwards;\r\n    opacity: 1;\r\n}\n\n/*******" +
                        "***LOADER*********/\r\n.cd-popup3 {\r\n    position: fixed;\r\n    left: 0;\r\n    top: " +
                        "0;\r\n    height: 100%;\r\n    width: 100%;\r\n    background-color: rgba(94, 110, 141" +
                        ", 0.9);\r\n    opacity: 0;\r\n    visibility: hidden;\r\n    -webkit-transition: opaci" +
                        "ty 0.3s 0s, visibility 0s 0.3s;\r\n    -moz-transition: opacity 0.3s 0s, visibilit" +
                        "y 0s 0.3s;\r\n    transition: opacity 0.3s 0s, visibility 0s 0.3s;\r\n    margin: au" +
                        "to;\r\n}\r\n\r\n    .cd-popup3.is-visible {\r\n        opacity: 1;\r\n        visibility: " +
                        "visible;\r\n        -webkit-transition: opacity 0.3s 0s, visibility 0s 0s;\r\n      " +
                        "  -moz-transition: opacity 0.3s 0s, visibility 0s 0s;\r\n        transition: opaci" +
                        "ty 0.3s 0s, visibility 0s 0s;\r\n    }\r\n\r\n\r\n@media only screen and (min-width: 117" +
                        "0px) {\r\n    .cd-popup-container2 {\r\n        margin: 8em auto;\r\n    }\r\n}\r\n\r\n.cd-p" +
                        "opup-container2 {\r\n    position: relative;\r\n    width: 90%;\r\n    max-width: 400p" +
                        "x;\r\n    margin: 4em auto;\r\n    border-radius: .25em .25em .4em .4em;\r\n    text-a" +
                        "lign: center;\r\n    -webkit-transform: translateY(-40px);\r\n    -moz-transform: tr" +
                        "anslateY(-40px);\r\n    -ms-transform: translateY(-40px);\r\n    -o-transform: trans" +
                        "lateY(-40px);\r\n    transform: translateY(-40px);\r\n    /* Force Hardware Accelera" +
                        "tion in WebKit */\r\n    -webkit-backface-visibility: hidden;\r\n    -webkit-transit" +
                        "ion-property: -webkit-transform;\r\n    -moz-transition-property: -moz-transform;\r" +
                        "\n    transition-property: transform;\r\n    -webkit-transition-duration: 0.3s;\r\n  " +
                        "  -moz-transition-duration: 0.3s;\r\n    transition-duration: 0.3s;\r\n}\r\n\r\ncd-popup" +
                        "-container2 {\r\n    margin: 0;\r\n    padding: 0;\r\n    border: 0;\r\n    font: inheri" +
                        "t;\r\n    vertical-align: baseline;\r\n}\r\n\r\n.is-visible .cd-popup-container2 {\r\n    " +
                        "-webkit-transform: translateY(0);\r\n    -moz-transform: translateY(0);\r\n    -ms-t" +
                        "ransform: translateY(0);\r\n    -o-transform: translateY(0);\r\n    transform: trans" +
                        "lateY(0);\r\n}\r\n\r\n\r\n.loader {\r\n    border: 16px solid #f3f3f3;\r\n    border-radius:" +
                        " 50%;\r\n    border-top: 16px solid #3498db;\r\n    width: 120px;\r\n    height: 120px" +
                        ";\r\n    -webkit-animation: spin 2s linear infinite; /* Safari */\r\n    animation: " +
                        "spin 2s linear infinite;\r\n    margin: auto;\r\n    margin-top: 60%;\r\n  \r\n}\r\n\r\n    " +
                        ".labelSuccess {\r\n        padding-left: 38%;\r\n        color: green;\r\n    }\r\n\n</st" +
                        "yle>\r\n\r\n<section>\r\n    <nav class=\"stroke\">\r\n        <ul>\r\n            <li>"));
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl1;
            @__ctrl1 = this.@__BuildControlhomePage();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</li>\r\n        </ul>\r\n    </nav>\r\n</section>\r\n\r\n\r\n"));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControlLabel1();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            global::System.Web.UI.UpdatePanel @__ctrl3;
            @__ctrl3 = this.@__BuildControlup_modal_popup();
            @__parser.AddParsedSubObject(@__ctrl3);
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
