//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCB_DPC_FRONT.WP_DPCAllCourses {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class WP_DPCAllCourses {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lbl_location;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlLocation;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ul_fee;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView tblTrainingCentre;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.Label Label1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.Label trainingCentreLable;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView tblCourse;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "15.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(WP_DPCAllCourses target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl_location() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lbl_location = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbl_location";
            @__ctrl.AssociatedControlID = "ddlLocation";
            @__ctrl.Text = "Mode of Training <span class=\'tooltip\'>*</span> <span class=\'mandatory\'>Mandatory" +
                " field</span>";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control3() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "Please select";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control4() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "Online";
            @__ctrl.Value = "1";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control5() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "Face To Face";
            @__ctrl.Value = "2";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void @__BuildControl__control2(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control3();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control4();
            @__ctrl.Add(@__ctrl2);
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control5();
            @__ctrl.Add(@__ctrl3);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlLocation() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlLocation = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlLocation";
            @__ctrl.AutoPostBack = true;
            this.@__BuildControl__control2(@__ctrl.Items);
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.ddlLocation_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.ddlLocation_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlul_fee() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("ul");
            this.ul_fee = @__ctrl;
            @__ctrl.ID = "ul_fee";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            <li>- Registration for course to be made via this platform ONLY.</li>
                            <li>- Course Fee: Rs 1,100</li>
                            <li>- Payment: By Bank Card or Cash</li>
                            <li>- In case of cash payment, the fee of Rs 1100 to be paid at MDPA Office (Ebene) prior to registration on this platform.</li>
                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control7() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.DataField = "Location";
            @__ctrl.HeaderText = "Training Centre";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControl__control10() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lnkSelect";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-primary");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "width:100px;");
            @__ctrl.Text = "Select";
            @__ctrl.CommandName = "Select";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control10);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        public void @__DataBinding__control10(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.LinkButton dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.LinkButton)(sender));
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.CommandArgument = global::System.Convert.ToString( Container.DataItemIndex , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void @__BuildControl__control9(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n                                        "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control10();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n                                    "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control8() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control9), null);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void @__BuildControl__control6(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.BoundField @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control7();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.WebControls.TemplateField @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control8();
            @__ctrl.Add(@__ctrl2);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControltblTrainingCentre() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.tblTrainingCentre = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "tblTrainingCentre";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "tblTrainingCentreCl");
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "custom-gridview";
            this.@__BuildControl__control6(@__ctrl.Columns);
            @__ctrl.RowCommand -= new System.Web.UI.WebControls.GridViewCommandEventHandler(this.tblTrainingCentre_RowCommand);
            @__ctrl.RowCommand += new System.Web.UI.WebControls.GridViewCommandEventHandler(this.tblTrainingCentre_RowCommand);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label1";
            @__ctrl.Visible = false;
            @__ctrl.Font.Bold = true;
            @__ctrl.Font.Size = global::System.Web.UI.WebControls.FontUnit.Large;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Margin-Left", "12%");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControltrainingCentreLable() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.trainingCentreLable = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "trainingCentreLable";
            @__ctrl.Visible = false;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "labelTraining");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control12() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.DataField = "ID";
            @__ctrl.HeaderText = "Id";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control13() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.DataField = "BatchNumber";
            @__ctrl.HeaderText = "Batch";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control14() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.DataField = "Batch_Reference";
            @__ctrl.HeaderText = "BatchRef";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control15() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.DataField = "Days";
            @__ctrl.HeaderText = "Days";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control16() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.DataField = "Time";
            @__ctrl.HeaderText = "Time";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control17() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.DataField = "Start_Date";
            @__ctrl.HeaderText = "Start Date";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control18() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.DataField = "Duration";
            @__ctrl.HeaderText = "Duration (Weeks)";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControl__control21() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lnkSelect_CourseDetails";
            @__ctrl.Text = "Apply";
            @__ctrl.CommandName = "Select";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control21);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        public void @__DataBinding__control21(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.LinkButton dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.LinkButton)(sender));
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.CommandArgument = global::System.Convert.ToString( Container.DataItemIndex , global::System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void @__BuildControl__control20(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n                                        "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control21();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n                                    "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control19() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control20), null);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void @__BuildControl__control11(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.BoundField @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control12();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.WebControls.BoundField @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control13();
            @__ctrl.Add(@__ctrl2);
            global::System.Web.UI.WebControls.BoundField @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control14();
            @__ctrl.Add(@__ctrl3);
            global::System.Web.UI.WebControls.BoundField @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control15();
            @__ctrl.Add(@__ctrl4);
            global::System.Web.UI.WebControls.BoundField @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control16();
            @__ctrl.Add(@__ctrl5);
            global::System.Web.UI.WebControls.BoundField @__ctrl6;
            @__ctrl6 = this.@__BuildControl__control17();
            @__ctrl.Add(@__ctrl6);
            global::System.Web.UI.WebControls.BoundField @__ctrl7;
            @__ctrl7 = this.@__BuildControl__control18();
            @__ctrl.Add(@__ctrl7);
            global::System.Web.UI.WebControls.TemplateField @__ctrl8;
            @__ctrl8 = this.@__BuildControl__control19();
            @__ctrl.Add(@__ctrl8);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControltblCourse() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.tblCourse = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "tblCourse";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "tblCourseCl");
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "custom-gridview";
            this.@__BuildControl__control11(@__ctrl.Columns);
            @__ctrl.RowCommand -= new System.Web.UI.WebControls.GridViewCommandEventHandler(this.tblCourseDetails_RowCommand);
            @__ctrl.RowCommand += new System.Web.UI.WebControls.GridViewCommandEventHandler(this.tblCourseDetails_RowCommand);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void @__BuildControlTree(global::NCB_DPC_FRONT.WP_DPCAllCourses.WP_DPCAllCourses @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\n\n<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-aweso" +
                        "me/4.7.0/css/font-awesome.min.css\" />\n\n<script type=\"text/javascript\" src=\"https" +
                        "://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\n<script t" +
                        "ype=\"text/javascript\" src=\"https://cdn.datatables.net/1.10.20/js/jquery.dataTabl" +
                        "es.min.js\"></script>\n<link href=\"https://cdn.datatables.net/1.10.20/css/jquery.d" +
                        "ataTables.css\" rel=\"stylesheet\" type=\"text/css\" />\n\n<script type=\"text/javascrip" +
                        "t\">\n    $(document).ready(function () {\n        $(\'.tblTrainingCentreCl\').DataTa" +
                        "ble(\n        {\n            bLengthChange: true,\n            lengthMenu: [[10, 25" +
                        ", 50, -1], [10, 25, 50, \'All\']],\n            bFilter: true,\n            bSort: t" +
                        "rue,\n            bPaginate: true\n        });\n\n        $(\'.tblCourseCl\').DataTabl" +
                        "e(\n        {\n            bLengthChange: true,\n            lengthMenu: [[10, 25, " +
                        "50, -1], [10, 25, 50, \'All\']],\n            bFilter: true,\n            bSort: tru" +
                        "e,\n            bPaginate: true\n        });\n    });\n</script>\n\n<style type=\"text/" +
                        "css\">\n    .auto-style1 {\n        height: 26px;\n    }\n    body {\r\n    font-family" +
                        ": Arial, Helvetica, sans-serif;\r\n}\r\n\r\n#s4-ribbonrow, .bottom-nav-container, .ms-" +
                        "cui-topBar2, .s4-notdlg, .s4-pr s4-ribbonrowhidetitle, .s4-notdlg noindex, #ms-c" +
                        "ui-ribbonTopBars, #s4-titlerow, #s4-pr s4-notdlg s4-titlerowhidetitle, #s4-leftp" +
                        "anel-content {\r\n    display: none !important;\r\n }\r\n\r\n\r\n    .center-label {\r\n    " +
                        "    text-align: center;\r\n    }\r\n\r\n    .bigger-size {\r\n        font-size: larger;" +
                        "\r\n    }\r\n\r\n\r\n/* .s4-ca { */\r\n    /* margin-left: 0px !important; */\r\n    /* marg" +
                        "in-right: 0px !important; */\r\n/* } */\r\n\r\n.ms-core-navigation { \r\n     display: n" +
                        "one; \r\n }\r\n\r\n/* #contentBox { */\r\n    /* margin-left: 0; */\r\n/* } */\r\n\r\n.ms-webp" +
                        "art-titleText {\r\n    display: none;\r\n}\r\n\r\n.removeCaps {\r\n    text-transform: non" +
                        "e !important;\r\n}\r\n\r\n/* The Modal (background) */\r\n.modal {\r\n    display: none; /" +
                        "* Hidden by default */\r\n    position: fixed; /* Stay in place */\r\n    z-index: 1" +
                        "; /* Sit on top */\r\n    padding-top: 100px; /* Location of the box */\r\n    left:" +
                        " 0;\r\n    top: 0;\r\n    width: 100%; /* Full width */\r\n    height: 100%; /* Full h" +
                        "eight */\r\n    overflow: auto; /* Enable scroll if needed */\r\n    background-colo" +
                        "r: rgb(0,0,0); /* Fallback color */\r\n    background-color: rgba(0,0,0,0.4); /* B" +
                        "lack w/ opacity */\r\n}\r\n\r\n/* Modal Content */\r\n.modal-content {\r\n    background-c" +
                        "olor: #fefefe;\r\n    margin: auto;\r\n    padding: 20px;\r\n    border: 1px solid #88" +
                        "8;\r\n    width: 80%;\r\n}\r\n\r\n/* The Close Button */\r\n.close {\r\n    color: #aaaaaa;\r" +
                        "\n    float: right;\r\n    font-size: 28px;\r\n    font-weight: bold;\r\n}\r\n\r\n    .clos" +
                        "e:hover,\r\n    .close:focus {\r\n        color: #000;\r\n        text-decoration: non" +
                        "e;\r\n        cursor: pointer;\r\n    }\r\n\r\n.DPCApplication {\r\n    max-width: 100%;\r\n" +
                        "}\r\n\r\n    .DPCApplication .form-row:not(#btnRow) {\r\n        display: flex;\r\n     " +
                        "   flex-wrap: wrap;\r\n        max-width: 80%;\r\n        margin: 0 auto;\r\n        f" +
                        "loat: none;\r\n    }\r\n\r\n#btnRow {\r\n    max-width: 85%;\r\n    margin: 0 auto;\r\n    f" +
                        "loat: none;\r\n    text-align: center;\r\n}\r\n\r\n.DPCApplication .form-fields.submit i" +
                        "nput {\r\n    width: 200px;\r\n    padding: 12px 30px;\r\n    margin: 0 auto;\r\n    bor" +
                        "der: none;\r\n    background-color: #799951;\r\n    color: #fff;\r\n    font-size: 20;" +
                        "\r\n    font-weight: 500;\r\n}\r\n\r\n.DPCApplication .form-fields.submit a {\r\n    text-" +
                        "decoration: none;\r\n    display: block;\r\n    width: 140px;\r\n    padding: 12px 30p" +
                        "x;\r\n    margin: 0 auto;\r\n    border: none;\r\n    background-color: #799951;\r\n    " +
                        "color: #fff;\r\n    font-size: 20;\r\n    font-weight: 500;\r\n}\r\n\r\n    .DPCApplicatio" +
                        "n .form-fields.submit input:hover, .DPCApplication .form-fields.submit a:hover {" +
                        "\r\n        background-color: #02AFEF;\r\n        cursor: pointer;\r\n    }\r\n\r\n.DPCApp" +
                        "lication .form-fields.submitTC input {\r\n    width: 250px;\r\n    padding: 12px 30p" +
                        "x;\r\n    margin: 0 auto;\r\n    border: none;\r\n    background-color: #799951;\r\n    " +
                        "color: #fff;\r\n    font-size: 20;\r\n    font-weight: 500;\r\n}\r\n\r\n    .DPCApplicatio" +
                        "n .form-fields.submitTC input:hover {\r\n        background-color: #02AFEF;\r\n     " +
                        "   cursor: pointer;\r\n    }\r\n\r\n#txt_trainingCentreCode {\r\n    margin-top: 4px;\r\n}" +
                        "\r\n\r\n.new-title-block {\r\n    width: 77%;\r\n    position: relative;\r\n    float: lef" +
                        "t;\r\n    margin-top: 30px;\r\n    margin-bottom: 15px;\r\n}\r\n\r\n.inner-sub-title {\r\n  " +
                        "  font-size: 52px;\r\n    font-weight: 700 !important;\r\n    color: #799951;\r\n}\r\n\r\n" +
                        ".sub-title {\r\n    font-size: 25px;\r\n    font-weight: 600 !important;\r\n    color:" +
                        " #799951;\r\n}\r\n\r\nspan.tooltip {\r\n    color: #ff0000;\r\n    font-size: 22px;\r\n    l" +
                        "ine-height: 26px;\r\n    cursor: pointer;\r\n}\r\n\r\nspan.mandatory {\r\n    background: " +
                        "#465159;\r\n    color: #fff;\r\n    font-size: 12px;\r\n    line-height: 18px;\r\n    di" +
                        "splay: inline-block;\r\n    margin-left: 10px;\r\n    opacity: 0;\r\n    visibility: h" +
                        "idden;\r\n    position: absolute;\r\n    max-width: 0;\r\n    padding: 5px 8px;\r\n    b" +
                        "order-radius: 3px;\r\n    transition: all 0.5s ease-out 0s;\r\n}\r\n\r\nspan.tooltip:hov" +
                        "er + span.mandatory {\r\n    opacity: 1;\r\n    visibility: visible;\r\n    max-width:" +
                        " 100%;\r\n}\r\n\r\n.form-fields {\r\n    position: relative;\r\n    margin: 2% 2% 0;\r\n}\r\n\r" +
                        "\n    .form-fields.w100 {\r\n        width: 100%;\r\n    }\r\n\r\n        .form-fields.w1" +
                        "00.field-med input, .form-fields.w100.field-med select {\r\n            width: 46%" +
                        ";\r\n        }\r\n\r\n        .form-fields.w100.field-sm input, .form-fields.w100.fiel" +
                        "d-sm select {\r\n            width: 29.3%;\r\n        }\r\n\r\n    .form-fields.w50 {\r\n " +
                        "       width: 46%;\r\n    }\r\n\r\n    .form-fields.w30 {\r\n        width: 29.3%;\r\n    " +
                        "}\r\n\r\n    .form-fields.w70 {\r\n        width: 65.7%;\r\n    }\r\n\r\n@media screen and (" +
                        "max-width: 900px) {\r\n    .form-fields.w100.field-sm input, .form-fields.w100.fie" +
                        "ld-sm select {\r\n        width: 100%;\r\n    }\r\n\r\n    .form-fields.w30 {\r\n        w" +
                        "idth: 100%;\r\n    }\r\n\r\n    .form-fields.w70 {\r\n        width: 100%;\r\n    }\r\n\r\n   " +
                        " .form-fields.w50 {\r\n        width: 100%;\r\n    }\r\n\r\n    .form-fields.w100.field-" +
                        "med input, .form-fields.w100.field-med select {\r\n        width: 100%;\r\n    }\r\n\r\n" +
                        "    .form-fields-sm-tit {\r\n        margin: 15px 0 0;\r\n    }\r\n\r\n    .form-fields " +
                        "{\r\n        position: relative;\r\n        margin: 5% 0 0;\r\n    }\r\n\r\n        .form-" +
                        "fields input[type=\'text\'], .form-fields select {\r\n            height: 40px;\r\n   " +
                        "     }\r\n}\r\n\r\n.form-row .form-fields label {\r\n    font-size: 14px;\r\n    line-heig" +
                        "ht: 22px;\r\n    font-weight: bold;\r\n    color: #000000a3;\r\n}\r\n\r\n.form-fields inpu" +
                        "t[type=\'text\'], .form-fields select {\r\n    width: 100%;\r\n    height: 35px;\r\n    " +
                        "border: 1px solid #c5c5c5;\r\n    font-size: 14px;\r\n    line-height: 22px;\r\n    co" +
                        "lor: #47515a;\r\n    border-radius: 0;\r\n    background-color: transparent;\r\n    te" +
                        "xt-transform: capitalize;\r\n    padding: 0 15px;\r\n}\r\n\r\n.form-fields textarea {\r\n " +
                        "   width: 100%;\r\n    min-height: 100px;\r\n    border: 1px solid #c5c5c5;\r\n    fon" +
                        "t-size: 14px;\r\n    line-height: 22px;\r\n    color: #47515a;\r\n    border-radius: 0" +
                        ";\r\n    background-color: transparent;\r\n    text-transform: capitalize;\r\n    padd" +
                        "ing: 15px;\r\n    margin-top: 4px;\r\n    font-family: \'Roboto\', sans-serif;\r\n}\r\n\r\n." +
                        "form-fields input[type=\'checkbox\'] {\r\n    margin-right: 3.5%;\r\n    height: 17px;" +
                        "\r\n    width: 17px;\r\n}\r\n\r\nlabel.lbl_days_text {\r\n    vertical-align: text-bottom;" +
                        "\r\n    font-size: 16px !important;\r\n    font-weight: 500 !important;\r\n}\r\n\r\n#tblCo" +
                        "urses {\r\n    border-collapse: collapse;\r\n    width: 100%;\r\n}\r\n\r\n    #tblCourses " +
                        "td, #tblCourses th {\r\n        border: 1px solid #ddd;\r\n        padding: 8px;\r\n  " +
                        "  }\r\n\r\n    #tblCourses tr:nth-child(even) {\r\n        background-color: #f2f2f2;\r" +
                        "\n    }\r\n\r\n    #tblCourses tr:hover {\r\n        background-color: #ddd;\r\n    }\r\n\r\n" +
                        "    #tblCourses thead {\r\n        padding-top: 12px;\r\n        padding-bottom: 12p" +
                        "x;\r\n        text-align: left;\r\n        background-color: #799951;\r\n        color" +
                        ": white;\r\n        font-weight: 600;\r\n    }\r\n\r\n.not-mandatory {\r\n    margin-top: " +
                        "4px;\r\n}\r\n\r\n.alert {\r\n    padding: 15px;\r\n    margin-bottom: 20px;\r\n    border: 1" +
                        "px solid transparent;\r\n    border-radius: 4px;\r\n    display: flex;\r\n    align-it" +
                        "ems: center;\r\n}\r\n\r\n    .alert:before {\r\n        content: \'\';\r\n        position: " +
                        "absolute;\r\n        width: 0;\r\n        height: calc(100% - 44px);\r\n        border" +
                        "-left: 1px solid;\r\n        border-right: 2px solid;\r\n        border-bottom-right" +
                        "-radius: 3px;\r\n        border-top-right-radius: 3px;\r\n        left: 0;\r\n        " +
                        "top: 50%;\r\n        transform: translate(0,-50%);\r\n        height: 20px;\r\n    }\r\n" +
                        "\r\n    .alert > .start-icon {\r\n        margin-right: 0;\r\n        min-width: 20px;" +
                        "\r\n        text-align: center;\r\n        margin-right: 5px;\r\n        float: left;\r" +
                        "\n    }\r\n\r\n.alert-simple.alert-info {\r\n    border: 1px solid rgba(6, 44, 241, 0.4" +
                        "6);\r\n    background-color: rgba(7, 73, 149, 0.12156862745098039);\r\n    box-shado" +
                        "w: 0px 0px 2px #0396ff;\r\n    color: #0396ff;\r\n    transition: 0.5s;\r\n}\r\n\r\n.alert" +
                        "-info:hover {\r\n    background-color: rgba(7, 73, 149, 0.35);\r\n    transition: 0." +
                        "5s;\r\n}\r\n\r\n#radioBtn_public {\r\n    margin-top: 10px;\r\n}\r\n\r\n#radioBtn_private {\r\n " +
                        "   margin-left: 10%;\r\n}\r\n\r\n\r\n.custom-gridview td, .custom-gridview th {\r\n    bor" +
                        "der: 1px solid #ddd;\r\n    padding: 8px;\r\n}\r\n\r\n.custom-gridview tr:nth-child(even" +
                        ") {\r\n    background-color: #f2f2f2;\r\n}\r\n\r\n.custom-gridview tr:hover {\r\n    backg" +
                        "round-color: #ddd;\r\n}\r\n\r\n.custom-gridview th {\r\n    padding-top: 12px;\r\n    padd" +
                        "ing-bottom: 12px;\r\n    text-align: left;\r\n    background-color: #799951;\r\n    co" +
                        "lor: white;\r\n}\r\n\r\n.custom-gridview tbody tr td a {\r\n    text-decoration: none;\r\n" +
                        "}\r\n\r\n.declaration {\r\n    color: red;\r\n}\r\n\r\n.declarationText {\r\n    display: inli" +
                        "ne-flex;\r\n    margin-top: 10px;\r\n    margin-left: 2%;\r\n    font-size: 14px;\r\n   " +
                        " font-weight: 500;\r\n}\r\n\r\n.inline {\r\n    display: inline-flex;\r\n    margin-top: 1" +
                        "0px;\r\n    font-size: 15px;\r\n}\r\n\r\n    .inline input {\r\n        margin-right: 8px;" +
                        "\r\n        margin-top: 3.5px;\r\n        font-size: 15px;\r\n    }\r\n\r\n    .inline lab" +
                        "el {\r\n        cursor: pointer;\r\n        margin-right: 25px;\r\n        font-size: " +
                        "15px;\r\n    }\n\n    body {\r\n    font-family: Arial, Helvetica, sans-serif;\r\n    pa" +
                        "dding: 0;\r\n    margin: 0;\r\n}\r\n\r\nh2 {\r\n    text-align: center;\r\n    font-size: 40" +
                        "px;\r\n    margin: 0;\r\n    font-weight: 300;\r\n    color: inherit;\r\n    padding: 50" +
                        "px;\r\n}\r\n\r\n.center {\r\n    text-align: center;\r\n}\r\n\r\nsection {\r\n    height: 5%;\r\n}" +
                        "\r\n\r\n/* NAVIGATION */\r\nnav {\r\n    width: 80%;\r\n    margin: 0 auto;\r\n    backgroun" +
                        "d: #fff;\r\n    padding: 5px 0;\r\n}\r\n\r\nnav ul {\r\n    list-style: none;\r\n    text-al" +
                        "ign: left;\r\n}\r\n\r\nnav ul li {\r\n    display: inline-block;\r\n}\r\n\r\nnav ul li a {\r\n  " +
                        "  display: block;\r\n    padding: 15px;\r\n    text-decoration: none;\r\n    color: #a" +
                        "aa;\r\n    font-weight: 600;\r\n    text-transform: uppercase;\r\n    margin: 0 10px;\r" +
                        "\n}\r\n\r\nnav ul li a,\r\nnav ul li a:after,\r\nnav ul li a:before {\r\n    transition: al" +
                        "l .5s;\r\n}\r\n\r\nnav ul li a:hover {\r\n    color: #555;\r\n}\r\n\r\n/* stroke */\r\nnav.strok" +
                        "e ul li a,\r\nnav.fill ul li a {\r\n    position: relative;\r\n}\r\n\r\nnav.stroke ul li a" +
                        ":after,\r\nnav.fill ul li a:after {\r\n    position: absolute;\r\n    bottom: 0;\r\n    " +
                        "left: 0;\r\n    right: 0;\r\n    margin: auto;\r\n    width: 0%;\r\n    content: \'.\';\r\n " +
                        "   color: transparent;\r\n    background: #333;\r\n    height: 1px;\r\n}\r\n\r\nnav.stroke" +
                        " ul li a:hover:after {\r\n    width: 100%;\r\n}\r\n\r\nnav.fill ul li a {\r\n    transitio" +
                        "n: all 2s;\r\n}\r\n\r\nnav.fill ul li a:after {\r\n    text-align: left;\r\n    content: \'" +
                        ".\';\r\n    margin: 0;\r\n    opacity: 0;\r\n}\r\n\r\nnav.fill ul li a:hover {\r\n    color: " +
                        "#023f1c;\r\n    z-index: 1;\r\n}\r\n\r\nnav.fill ul li a:hover:after {\r\n    z-index: -10" +
                        ";\r\n    animation: fill 1s forwards;\r\n    -webkit-animation: fill 1s forwards;\r\n " +
                        "   -moz-animation: fill 1s forwards;\r\n    opacity: 1;\r\n}\n\n/**********LOADER*****" +
                        "****/\r\n.cd-popup3 {\r\n    position: fixed;\r\n    left: 0;\r\n    top: 0;\r\n    height" +
                        ": 100%;\r\n    width: 100%;\r\n    background-color: rgba(94, 110, 141, 0.9);\r\n    o" +
                        "pacity: 0;\r\n    visibility: hidden;\r\n    -webkit-transition: opacity 0.3s 0s, vi" +
                        "sibility 0s 0.3s;\r\n    -moz-transition: opacity 0.3s 0s, visibility 0s 0.3s;\r\n  " +
                        "  transition: opacity 0.3s 0s, visibility 0s 0.3s;\r\n    margin: auto;\r\n}\r\n\r\n    " +
                        ".cd-popup3.is-visible {\r\n        opacity: 1;\r\n        visibility: visible;\r\n    " +
                        "    -webkit-transition: opacity 0.3s 0s, visibility 0s 0s;\r\n        -moz-transit" +
                        "ion: opacity 0.3s 0s, visibility 0s 0s;\r\n        transition: opacity 0.3s 0s, vi" +
                        "sibility 0s 0s;\r\n    }\r\n\r\n\r\n@media only screen and (min-width: 1170px) {\r\n    .c" +
                        "d-popup-container2 {\r\n        margin: 8em auto;\r\n    }\r\n}\r\n\r\n.cd-popup-container" +
                        "2 {\r\n    position: relative;\r\n    width: 90%;\r\n    max-width: 400px;\r\n    margin" +
                        ": 4em auto;\r\n    border-radius: .25em .25em .4em .4em;\r\n    text-align: center;\r" +
                        "\n    -webkit-transform: translateY(-40px);\r\n    -moz-transform: translateY(-40px" +
                        ");\r\n    -ms-transform: translateY(-40px);\r\n    -o-transform: translateY(-40px);\r" +
                        "\n    transform: translateY(-40px);\r\n    /* Force Hardware Acceleration in WebKit" +
                        " */\r\n    -webkit-backface-visibility: hidden;\r\n    -webkit-transition-property: " +
                        "-webkit-transform;\r\n    -moz-transition-property: -moz-transform;\r\n    transitio" +
                        "n-property: transform;\r\n    -webkit-transition-duration: 0.3s;\r\n    -moz-transit" +
                        "ion-duration: 0.3s;\r\n    transition-duration: 0.3s;\r\n}\r\n\r\ncd-popup-container2 {\r" +
                        "\n    margin: 0;\r\n    padding: 0;\r\n    border: 0;\r\n    font: inherit;\r\n    vertic" +
                        "al-align: baseline;\r\n}\r\n\r\n.is-visible .cd-popup-container2 {\r\n    -webkit-transf" +
                        "orm: translateY(0);\r\n    -moz-transform: translateY(0);\r\n    -ms-transform: tran" +
                        "slateY(0);\r\n    -o-transform: translateY(0);\r\n    transform: translateY(0);\r\n}\r\n" +
                        "\r\n\r\n.loader {\r\n    border: 16px solid #f3f3f3;\r\n    border-radius: 50%;\r\n    bor" +
                        "der-top: 16px solid #3498db;\r\n    width: 120px;\r\n    height: 120px;\r\n    -webkit" +
                        "-animation: spin 2s linear infinite; /* Safari */\r\n    animation: spin 2s linear" +
                        " infinite;\r\n    margin: auto;\r\n    margin-top: 60%;\r\n}\r\n\r\n    .labelTraining {\r\n" +
                        "        color: Green;\r\n        padding-left: 11.5%;\r\n        font-size: larger;\r" +
                        "\n    }\r\n\n</style>\n\n<div id=\"content-container\">\n    <div class=\"cnWrapper\">\r\n   " +
                        " <div class=\"DPCApplication\">\r\n        <form>\r\n            <div class=\"form-row " +
                        "new-title-block\">\r\n                <h3 class=\"inner-sub-title\">Digital Proficien" +
                        "cy Course (DPC)</h3>\r\n            </div>\r\n            <div class=\"form-row\">\r\n  " +
                        "              <div class=\"form-fields w30\">\r\n                    "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllbl_location();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            @__ctrl2 = this.@__BuildControlddlLocation();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n\r\n                <div class=\"form-fields w50\">\r\n      " +
                        "              <div style=\"border: 1px solid #ccc; padding: 20px;\">\r\n            " +
                        "            <p><strong>Course Registration</strong></p>\r\n                       " +
                        " "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl3;
            @__ctrl3 = this.@__BuildControlul_fee();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </div>\r\n                </div>\r\n            </div>\n\n       " +
                        "         <div class=\"form-row\" id=\"trainingCentre_tbl\">\n                    <div" +
                        " class=\"form-fields w100\">\n                        "));
            global::System.Web.UI.WebControls.GridView @__ctrl4;
            @__ctrl4 = this.@__BuildControltblTrainingCentre();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n                    </div>\n                </div>\r\n\r\n            <div class=\"for" +
                        "m-row\">\r\n                <div class=\"form-fields w100 center-label\">\r\n          " +
                        "          "));
            global::System.Web.UI.WebControls.Label @__ctrl5;
            @__ctrl5 = this.@__BuildControlLabel1();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n            </div>\r\n\r\n            "));
            global::System.Web.UI.WebControls.Label @__ctrl6;
            @__ctrl6 = this.@__BuildControltrainingCentreLable();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n            <div class=\"form-row\" id=\"courses_tbl\">\r\n                <div c" +
                        "lass=\"form-fields w100\">\n\n                        <h4 ID=\"trainingCentreId\"></h4" +
                        ">\n\n                        "));
            global::System.Web.UI.WebControls.GridView @__ctrl7;
            @__ctrl7 = this.@__BuildControltblCourse();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                    </div>
                </div>

                <script>
                    $(document).ready(function () {


                        $('.tblTrainingCentre').DataTable(
                            {
                                bLengthChange: true,
                                lengthMenu: [[10, 25, 50, -1], [10, 25, 50, 'All']],
                                bFilter: true,
                                bSort: true,
                                bPaginate: true
                            });

                        $('.tblCourse').DataTable(
                            {
                                bLengthChange: true,
                                lengthMenu: [[10, 25, 50, -1], [10, 25, 50, 'All']],
                                bFilter: true,
                                bSort: true,
                                bPaginate: true
                            });
                    });
                </script>

            </form>
        </div>
    </div>
</div>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
